name: xlo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.7
  rxdart: ^0.23.1
  brasil_fields: ^0.0.7+2
  image_picker: ^0.6.2+3
  cached_network_image: ^2.0.0-rc
  parse_server_sdk: ^1.0.24
  geolocator: ^5.1.5
  url_launcher: ^5.4.0
  carousel_pro: ^1.0.0
  path_provider: ^1.5.1
  flutter_image_compress: ^0.6.3
  transparent_image: ^1.0.0
  flutter_masked_text: ^0.8.0
  provider: ^3.2.0
  shared_preferences: ^0.5.6
  connectivity: ^0.4.6+1
  onesignal_flutter: ^2.0.2
  image_cropper: ^1.1.1
  location_permissions: ^2.0.3
  dio: ^3.0.7


  # flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

  assets:
    - images/
